### ISSUE TITLE
Illegal escape sequence ? & <a> cannot appear as a descendant of <a> ??

### ISSUE THREAD

**Issue by M-Saeb** [chakra-ui/frontity-chakra-ui-theme#8] opened 2020-02-12 14:13 UTC
I ran the frontity chakra theme I just installed from this Github repo and once I ran it I got following errors in the Devtools console: 
- 5 errors had the same text:
```
You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences
```
2 of them were from the path `eval @  webpack-internal:///…e.browser.esm.js:14` and
3 of them were from the path `serializeStyles @ webpack-internal:///…e.browser.esm.js:12`

- and 2 errors that were as follows:
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by Context.Consumer)
    in PseudoBox
    in Unknown (created by PostCategories)
    in div (created by Context.Consumer)
    in PseudoBox (created by PostCategory)
    in PostCategory (created by PostCategories)
    in div (created by Context.Consumer)
    in Box (created by Flex)
    in Flex (created by PostCategories)
    in PostCategories (created by PrimaryPostPreview)
    in div (created by Context.Consumer)
    in Box (created by PostContent)
    in PostContent (created by PrimaryPostPreview)
    in article (created by Context.Consumer)
    in Box (created by PrimaryPostArticle)
    in PrimaryPostArticle (created by PrimaryPostPreview)
    in a (created by Context.Consumer)
    in PseudoBox
    in Unknown (created by PrimaryPostPreview)
    in PrimaryPostPreview (created by FeaturedPostSection)
    in div (created by Context.Consumer)
    in Box (created by FeaturedPostSection)
    in section (created by Context.Consumer)
    in Box (created by Flex)
    in Flex (created by FeaturedPostSection)
    in FeaturedPostSection
    in section (created by Context.Consumer)
    in Box
    in Unknown
    in Unknown (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef
    in main (created by Context.Consumer)
    in Box
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider
    in Unknown (created by App)
    in HelmetProvider (created by App)
    in App
```
both of them were from the path `warningWithoutStack @ webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:179
`

PS: my OS is windows 10

**Comment by luisherranz** [comment] 2020-02-12 15:32
As far as I know, the `illegal escape sequence in your template literal` error comes from the Chakra library itself.

@segunadebayo can you please confirm that?

----

The `<a> cannot appear as a descendant of <a>` warning is legit because this theme is currently using a `Link` here for the featured posts:
https://github.com/chakra-ui/frontity-chakra-ui-theme/blob/master/packages/frontity-chakra-theme/src/components/featured-post/featured-post.js#L19-L28
that contains a `PostCategory` component that also contains `Link`:
https://github.com/chakra-ui/frontity-chakra-ui-theme/blob/master/packages/frontity-chakra-theme/src/components/post/post-categories.js#L38-L41
so it's actually a problem with the layout.

There are some tricks to solve it:
- https://css-tricks.com/nested-links/
- https://spectrum.chat/codepen/general/thought-excercise-nested-links~e45da96d-cd4d-4bd5-b785-44cee6b60e74?m=MTUzNTczMjc1NTE4MQ==

but I guess the limitation is there for a reason and it should not use nested links. Instead, it should have a container with the two links and just position them accordingly to occupy the correct space for each one so you cannot accidentally click on the big one if you are trying to click in the small one.

**Comment by luisherranz** [comment] 2020-02-12 15:40
Maybe a layout like this would be nice for accessibility so people don't accidentally click the wrong link on small mobile devices:

![aww-board](https://user-images.githubusercontent.com/3305402/74350568-cc455c00-4dad-11ea-8e70-674b86a0de69.png)

What do you think @segunadebayo? :)

**Comment by luisherranz** [comment] 2020-02-14 11:01
> As far as I know, the illegal escape sequence in your template literal error comes from the Chakra library itself.

My bad, it looks like it's an Emotion bug: https://github.com/emotion-js/emotion/issues/1755

**Comment by Andarist** [comment] 2020-02-27 16:26
The fix for this should be released in emotion soon 🔜 

Please test it once it gets released and let me know if it has resolved your issue.

**Comment by luisherranz** [comment] 2020-02-27 18:55
That's awesome. Thanks @Andarist!

**Comment by Koli14** [comment] 2020-04-01 08:00
@Andarist I still get the  error messages:
```
You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences
```
I use "emotion-theming": "10.0.27".

**Comment by Andarist** [comment] 2020-04-01 09:51
@Koli14 please provide a runnable repro case without such I can't validate your report.

**Comment by Koli14** [comment] 2020-04-01 12:02
@Andarist here is a runnable repo: [szinhaz.live](https://github.com/Koli14/szinhaz.live).
The exact steps to reproduce:
```
git clone git@github.com:Koli14/szinhaz.live.git
cd szinhaz.live/
npm install
npx frontity dev
```

**Comment by luisherranz** [comment] 2020-04-01 15:40
@Koli14 it would be really helpful if you could identify the exact component that is causing the problem.

If it is hard to identify, try deleting different sections of your site until you find out the one section that contains the component. Then, delete individual components in that section until you find the failing one.

**Comment by Andarist** [comment] 2020-04-01 16:12
Is there an easy way to disable source maps when using frontity? Those eval source maps ain't helping me when trying to debug this 😅

**Comment by luisherranz** [comment] 2020-04-01 16:39
Hooking into webpack is on the works 😅 

But you can change the source maps in the `node_modules/@frontity/core/dist/src/config/webpack/devtool.js` file until then.

**Comment by Andarist** [comment] 2020-04-02 08:08
After diving into this - it's pretty much the same issue as [this one](https://github.com/emotion-js/emotion/pull/1761#issuecomment-592048817), just with Babel output (instead of TS). This is caused by handing already transpiled code (`@chakra-ui/core`) to the Emotion plugin. 

It shouldn't be that hard to fix - I'll give it a shot soon.

**Comment by luisherranz** [comment] 2020-04-02 08:49
Thanks @Andarist. Is there something that can be done in `@chakra-ui/core` or it has to be fixed in Emotion?

**Comment by Andarist** [comment] 2020-04-02 09:58
I've prepared a fix for this in Emotion, you can take a look - https://github.com/emotion-js/emotion/pull/1829

**Comment by luisherranz** [comment] 2020-04-02 19:37
That is really awesome @Andarist! 😄

**Comment by Andarist** [comment] 2020-04-03 08:32
babel-plugin-emotion@10.0.33 has been released. Could you confirm that using it fixes your problem?

**Comment by Koli14** [comment] 2020-04-03 08:54
Thanks @Andarist , yes it solves the problem! :+1:

**Closed as completed** 2020-05-07 13:59 UTC
